name: Python CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest --maxfail=1 --disable-warnings -q

    - name: Deployment step
      if: success()   # Only run if tests pass
      run: bash deploy.sh
